kind: ResourceQuota
apiVersion: v1

metadata:
  name: cloudcart-rq
  namespace: cloudcart-ns

spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"

    limits.cpu: "4"
    limits.memory: "4Gi"

    pods: "10"
