---

name: Check code Quality

on: 
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository code
       uses: actions/checkout@v4

     - name: Set up python
       uses: actions/setup-python@v7
       with:
          python-version: '3.12'

     - name: Install Dependencies
       run: pip install -r requirements.txt

     - name: Run the linter
       run: pylint app.py

     - name: Run the scanning security vulnerabilities
       run: bandit -r app.py
