name: DevSecOps end-to-end pipeline

on: 
  workflow_dispatch: 
    
jobs:

  code-quality:
        uses: ./.github/workflows/codelint.yml

  dependency-scan:
        uses: ./.github/workflows/dependencies.yml

  secrets-scan:
        uses: ./.github/workflows/secret_scanning.yml

  docker-lint:
        needs: [secrets-scan, dependency-scan, code-quality]
        uses: ./.github/workflows/dockerfile-lint.yml

  build-push:
        needs: docker-lint
        uses: ./.github/workflows/docker-build.yml
        secrets: inherit
      
    
