name: Test self hosted-runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Test runner
        run: |
          echo "Running on self hosted runner"
          hostname
          kubectl version

